### ISSUE TITLE
Unacceptable performance degradation between gst v1.10.0 and v1.14.4

### ISSUE THREAD

**Issue by denis-shienkov** [Freescale/gstreamer-imx#232] opened 2019-07-02 10:46 UTC
I have an embedded device, based on "apalis-imx6".

Previously, I had an yocto Linux BSP image based on a "pyro" layer with the GStreamer v1.10.0.

using following pipeline to see the web-camera stream:

> gst-launch-1.0 v4l2src ! image/jpeg,width=1920,height=1080,framerate=30/1 ! imxvpudec ! imxipuvideosink sync=false

I had the CPU load ~8 %

But, right now, after updating to the yocto layer "thud", with the GStreamer v1.14.4

I had the CPU load ~45%

A degradation is about 5-6 times... that is not acceptable.

> root@apalis-imx6:~# gst-inspect-1.0 imxvpudec
> Factory Details:
>   Rank                     primary + 1 (257)
>   Long-name                Freescale VPU video decoder
>   Klass                    Codec/Decoder/Video
>   Description              hardware-accelerated video decoding using the Freescale VPU engine
>   Author                   Carlos Rafael Giani <dv@pseudoterminal.org>
> 
> Plugin Details:
>   Name                     imxvpu
>   Description              video en- and decoder elements using the Freescale i.MX VPU
>   Filename                 /usr/lib/gstreamer-1.0/libgstimxvpu.so
>   Version                  0.13.0
>   License                  LGPL
>   Source module            gstreamer-imx
>   Binary package           Unknown package release
>   Origin URL               Unknown package origin

> root@apalis-imx6:~# gst-inspect-1.0 v4l2src
> Factory Details:
>   Rank                     primary (256)
>   Long-name                Video (video4linux2) Source
>   Klass                    Source/Video
>   Description              Reads frames from a Video4Linux2 device
>   Author                   Edgard Lima <edgard.lima@gmail.com>, Stefan Kost <ensonic@users.sf.net>
> 
> Plugin Details:
>   Name                     video4linux2
>   Description              elements for Video 4 Linux
>   Filename                 /usr/lib/gstreamer-1.0/libgstvideo4linux2.so
>   Version                  1.14.4
>   License                  LGPL
>   Source module            gst-plugins-good
>   Source release date      2018-10-02
>   Binary package           GStreamer Good Plug-ins source release
>   Origin URL               Unknown package origin

> root@apalis-imx6:~# gst-inspect-1.0 --version
> gst-inspect-1.0 version 1.14.4
> GStreamer 1.14.4

**Comment by philn** [comment] 2019-09-06 09:11
Probable duplicate of #228 ?

**Comment by angolini** [comment] 2021-08-18 15:27
Could you, please, test it again using the latest release and update the status of this issue @denis-shienkov  or @philn ?

**Closed** 2021-09-21 12:59 UTC
