### ISSUE TITLE
imxg2dvideotransform: wrong transformation with crop metadata

### ISSUE THREAD

**Issue by angelobt** [Freescale/gstreamer-imx#303] opened 2022-02-07 09:44 UTC
Hi,

running this pipeline

GST_DEBUG=2 gst-launch-1.0 videotestsrc ! 'video/x-raw, width=720, height=576, framerate=25/1, format=UYVY' ! videocrop left=16 right=16 top=48 bottom=48  ! imxg2dvideotransform ! 'video/x-raw, width=688, height=480, framerate=25/1' ! imxg2dvideosink

I get this output

![image](https://user-images.githubusercontent.com/11391293/152763309-f5eb06d4-b113-4ce0-8a34-b6289313c997.png)

Please could you help me understand what I'm missing ?

**Comment by angelobt** [comment] 2022-02-07 13:02
I forget to say environment:

cpu: imx6Solo
yocto: hardknott
kernel: 5.10.35

**Comment by dv1** [comment] 2022-04-14 09:03
I can reproduce this in current OE master. This only happens if `videocrop` is inserted. I'm looking into it. Keep in mind though that `videocrop` will copy pixels via the CPU. The imxg2dvideotransform element supports the `GstVideoCropMeta`. I currently do not know though if that meta can be inserted as an alternative to copying pixels via the `videocrop` element.

**Comment by dv1** [comment] 2022-04-14 10:51
Sorry, closed by mistake. I added a fix for this issue in 5a3dcaae186a22ce548847c63f6abdeed4909275 . Please check if this also fixes the problem for you.

**Comment by dv1** [comment] 2023-06-28 20:21
Closing this due to inactivity - issue is assumed to have been fixed by the aforementioned commit. If this is not the case, reopen please.

**Closed by dv1** 2023-06-28 20:21 UTC
