### ISSUE TITLE
Screen corruption sometimes when closing imxg2dvideosink

### ISSUE THREAD

**Issue by DuBistKomisch** [Freescale/gstreamer-imx#120] opened 2016-09-22 14:17 UTC
I'm using SolidRun's kernel on a Cubox-i4p (imx6q). I'm using latest gstreamer-imx.

I've observed that sometimes when using `imxg2dvideosink`, when the pipeline is cleaned up, the screen suddenly corrupts like this:

![dsc_0165](https://cloud.githubusercontent.com/assets/703055/18750683/82c33da8-811f-11e6-935f-ce6b26afb490.JPG)

Usually it would still be showing the last frame, which in this case is a solid blue background with some white text over it.

My test pipeline is: `filesrc location=test.png ! pngparse ! pngdec ! imxg2dvideosink`

I've tried `tee`ing the data just before the sink back out to a file and it's fine, so it doesn't seem to be anything within the pipeline. A few times while doing this, the file encode/write delayed the cleaning up of the pipeline enough to see that the correct image was shown, and then suddenly became corrupt when cleaning up.

The issue seems to happen more and more often over time. From a fresh boot, it took 55 tries before it happened, but before rebooting I managed to get it to happen 90% of the time after a lot of testing. Obviously ideally we would be reusing the sink and swapping stuff out in the pipeline, but this seems to suggest there's something going wrong on a lower level.

Doing it with or without vsync doesn't make a difference. I can't get this to happen at all with `imxipuvideosink`, so I'm going to use that as a workaround for now.

**Comment by dv1** [comment] 2016-09-30 11:48
This seems more like a GPU driver bug. Have you tried to contact SolidRun about this? They maintain their own kernel fork for their machines.

**Comment by DuBistKomisch** [comment] 2016-10-03 09:30
I'll send them an email and report back. I am on their (our your) latest `3.14-1.0.x-mx6`(`-sr`) line kernel for reference, maybe something's been fixed in `3.14-1.1.x-imx`?

**Comment by linux4kix** [comment] 2016-10-06 09:32
Can you please provide the test.png you are using and the resolution of the display you are running?  I have been running a loop all morning and been unable to reproduce this issue.  Also are you running on a framebuffer, X11, or Wayland as your display?

**Comment by DuBistKomisch** [comment] 2016-10-06 10:02
Sure, here's the original image: http://vivi-misc.s3.amazonaws.com/test/test.png

Display is 1920x1080. Running on a framebuffer.

**Comment by linux4kix** [comment] 2016-10-06 10:06
Anything else I need to do?  I am just running watch gst-launch-1.0 filesrc
location=test.png ! pngparse ! pngdec ! imxg2dvideosink  which re-runs it
every 2 seconds.

**Comment by DuBistKomisch** [comment] 2016-10-06 10:13
I used a bash script with `sleep 5` from memory, but I just reproduced it once using `watch` as well.

**Comment by linux4kix** [comment] 2016-10-06 11:03
and you are running the 3.14.60-fslc-imx6-sr kernel with the latest GPU drivers installed?  If you do apt-get update you do not get any packages listed?

**Comment by DuBistKomisch** [comment] 2016-10-06 11:48
`uname -a` just says 3.14.54+, but also that I built it on Feb 2, which was just before you merged 3.14.60 in, so presumably this kernel is 3.14.59.

I'm not entirely sure how to check GPU driver versions, but the `libg2d0.8` package we have installed says `imx-gpu-viv version 5.0.11.p4.1-hfp-r0`. Where would I find what the latest version is?

We're on debian jessie, so `apt-get upgrade` just gives me a bunch of security updates I haven't got around to installing.

**Comment by linux4kix** [comment] 2016-10-06 12:00
apt-cache show libg2d0.8

shows 5.0.11.p4.5+6 for me.

**Comment by DuBistKomisch** [comment] 2016-10-06 12:03
Seems like a likely culprit... do Freescale/SolidRun provide a PPA for drivers? I'll try to build them myself otherwise.

**Comment by linux4kix** [comment] 2016-10-06 12:59
If you are using SolidRun's Debian image from https://images.solid-build.xyz
then our repositories are already included.  That is why I was asking if
you had done a full apt-get upgrade.

**Comment by DuBistKomisch** [comment] 2016-10-06 13:06
I wasn't aware SolidRun provided images. I'm using our own image we've put together over the past two years. I'll have a play around tomorrow to see if I can get it updated based on those.

**Comment by DuBistKomisch** [comment] 2016-10-07 08:06
Managed to hack it together by creating a dummy package to provide `galcore` to satisfy the deps. Latest drivers seem to have fixed the issue!

**Comment by linux4kix** [comment] 2016-10-07 11:16
great.  thanks for testing.

**Comment by DuBistKomisch** [comment] 2016-10-11 10:48
Actually after rebooting it seems to happen even more... very weird.

**Comment by DuBistKomisch** [comment] 2016-10-13 01:10
I was ready to write this off as a hardware issue, because my dev box does it pretty much every time now, but it's been spotted on a Hummingboard unit while testing our next release. Using latest drivers still.

**Comment by dv1** [comment] 2016-11-02 07:18
I will close this for now, since it seems to be SolidRun hardware specific, not a general gstreamer-imx issue. Please continue your correspondence with SolidRun, and if it turns out to actually be a gstreamer-imx problem, feel free to reopen the issue.

**Closed by dv1** 2016-11-02 07:18 UTC
