### ISSUE TITLE
SIGSEV when attempting to capture single frame from from imxv4l2videosrc

### ISSUE THREAD

**Issue by dpickford** [Freescale/gstreamer-imx#42] opened 2015-06-19 00:13 UTC
Hello, 

Thanks for the hardwork on the gstreamer-imx plugins, it's made a huge difference in video encoding performance.   We have been using the h264 encoding on the imx and it's been working well.   We're using the latest branch from about a week ago (0.10.2).

However, I'm working on doing various camera sensor tests to determine how well the ov5640 performs in low-light conditions and am trying to finish out my sensor-bakeoff test bed.   To do the image capture I'm using a simple gstreamer pipeline to capture a single image.  I've tried other encoders but get a similar error.

Here is the pipeline:

gst-launch-1.0 imxv4l2videosrc num-buffers=2 !  jpegenc ! filesink location=sample.jpeg

I'm using the same gstreamer pipeline on multiple other linux boxes (some with USB v4l2 camera, some parallel cameras).  Am I missing something fundamental here, or could this be a bug?

Thanks for your help.

Please let me know if you need any additional information.

Error logs below:

root@alpha1-cam:~# gst-launch-1.0 imxv4l2videosrc num-buffers=2 !  jpegenc ! filesink location=sample.jpeg
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Got EOS from element "pipeline0".
Execution ended after 0:00:00.403726333
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Caught SIGSEGV
#0  __libc_do_syscall ()
#1  0x76d963e2 in __libc_waitpid (pid=23817, stat_loc=<optimized out>, 
#2  0x76de426c in g_on_error_stack_trace ()
#3  0x0000c622 in fault_spin () at gst-launch.c:99
#4  fault_handler_sighandler (signum=<optimized out>) at gst-launch.c:90
#5  <signal handler called>
#6  0x76f86276 in gst_imx_v4l2_buffer_pool_free_buffer ()
#7  0x76ef1f70 in default_stop (pool=0x2137050) at gstbufferpool.c:382
#8  0x76f86582 in gst_imx_v4l2_buffer_pool_stop ()
#9  0x76ef1d9e in do_stop (pool=0x2137050) at gstbufferpool.c:402
#10 0x76ef272a in gst_buffer_pool_set_active (pool=0x2137050, active=0)
#11 0x76b2441a in gst_base_src_activate_pool (basesrc=<optimized out>, 
#12 0x76b24524 in gst_base_src_set_flushing (basesrc=0x2126068, flushing=1, 
#13 0x76b24a98 in gst_base_src_stop (basesrc=0x2126068) at gstbasesrc.c:3402
#14 0x76b29baa in gst_base_src_activate_push (active=<optimized out>, 
#15 gst_base_src_activate_mode (pad=0x2128018, parent=0x2126068, 
#16 0x76f1440c in gst_pad_activate_mode (pad=0x2128018, 
#17 0x76f14b8e in gst_pad_set_active (pad=0x2128018, active=0) at gstpad.c:969
#18 0x76eff010 in activate_pads (vpad=<optimized out>, ret=0x7eb0f580, 
#19 0x76f0a7ec in gst_iterator_fold (it=0x212d158, 
#20 0x76eff23a in iterator_activate_fold_with_resync (iter=0x212d158, 
#21 0x76f008c2 in gst_element_pads_activate (element=0x2126068, active=0)
#22 0x76f00b62 in gst_element_change_state_func (element=0x2126068, 
#23 0x76b284c8 in gst_base_src_change_state (element=0x2126068, 
#24 0x76f02042 in gst_element_change_state (element=0x2126068, 
#25 0x76f0270a in gst_element_set_state_func (element=0x2126068, 
#26 0x76f01e5a in gst_element_set_state (element=0x2126068, 
#27 0x76eee7bc in gst_bin_element_set_state (next=GST_STATE_READY, 
#28 gst_bin_change_state_func (element=0x2130058, 
#29 0x76f196fe in gst_pipeline_change_state (element=0x2130058, 
#30 0x76f02042 in gst_element_change_state (element=0x2130058, 
#31 0x76f0270a in gst_element_set_state_func (element=0x2130058, 
#32 0x76f01e5a in gst_element_set_state (element=0x2130058, 
#33 0x0000b35a in main (argc=8, argv=0x7eb0fc54) at gst-launch.c:1142
Spinning.  Please run 'gdb gst-launch-1.0 23813' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core.

**Comment by dv1** [comment] 2015-06-19 10:25
Interesting. I remember doing a similar test, and no segfault occurred. I'll check, thanks for the report.

**Comment by dv1** [comment] 2015-07-28 18:28
imxv4l2videosrc has been patched considerably since this issue was reported. Please re-check if it works now. Also run your pipeline with the GST_DEBUG environment variable set to "2,*imx*:9" , like this:

`GST_DEBUG=2,*imx*:9 gst-launch-1.0 imxv4l2videosrc num-buffers=2 ! jpegenc ! filesink location=sample.jpeg`

**Comment by dv1** [comment] 2015-10-30 20:42
Closing this for now, since nothing else was reported, and the issue could not be reproduced.

**Comment by cottrelld** [comment] 2015-11-03 03:04
This still SIGSEGV's.  Output is as follows:

~# GST_DEBUG=2,*imx*:9 gst-launch-1.0 imxv4l2videosrc num-buffers=2 ! jpegenc ! filesink location=sample.jpeg
0:00:00.554822667  2228  0x157d6a0 INFO         imxv4l2videosrc ../src/v4l2src/v4l2src.c:398:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0> get caps filter (NULL)
0:00:00.555394000  2228  0x157d6a0 INFO         imxv4l2videosrc ../src/v4l2src/v4l2src.c:409:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0> get caps video/x-raw, format=(string)I420, width=(int)[ 16, 2147483647 ], height=(int)[ 16, 2147483647 ], interlace-mode=(string)progressive, framerate=(fraction)[ 0/1, 100/1 ], pixel-aspect-ratio=(fraction)[ 0/1, 100/1 ]
0:00:00.558411333  2228  0x157d6a0 INFO         imxv4l2videosrc ../src/v4l2src/v4l2src.c:398:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0> get caps filter (NULL)
0:00:00.558712000  2228  0x157d6a0 INFO         imxv4l2videosrc ../src/v4l2src/v4l2src.c:409:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0> get caps video/x-raw, format=(string)I420, width=(int)[ 16, 2147483647 ], height=(int)[ 16, 2147483647 ], interlace-mode=(string)progressive, framerate=(fraction)[ 0/1, 100/1 ], pixel-aspect-ratio=(fraction)[ 0/1, 100/1 ]
Setting pipeline to PAUSED ...
0:00:00.561870000  2228  0x157d6a0 LOG          imxv4l2videosrc ../src/v4l2src/v4l2src.c:208:gst_imx_v4l2src_start:<imxv4l2videosrc0> start
0:00:01.427539333  2228  0x157d6a0 DEBUG        imxv4l2videosrc ../src/v4l2src/v4l2src.c:150:gst_imx_v4l2src_capture_setup:<imxv4l2videosrc0> pixelformat = 842093913  field = 0
0:00:01.427802667  2228  0x157d6a0 INFO         imxv4l2videosrc ../src/v4l2src/v4l2src.c:163:gst_imx_v4l2src_capture_setup:<imxv4l2videosrc0> capture mode 0: 640x480
0:00:01.803599000  2228  0x157d6a0 LOG              imxfdobject ../src/common/fd_object.c:59:gst_fd_object_new: new 0x1574450 with FD 6
0:00:01.803865000  2228  0x157d6a0 DEBUG        imxv4l2videosrc ../src/v4l2src/v4l2src.c:224:gst_imx_v4l2src_start:<imxv4l2videosrc0> width = 640
0:00:01.804026334  2228  0x157d6a0 DEBUG        imxv4l2videosrc ../src/v4l2src/v4l2src.c:225:gst_imx_v4l2src_start:<imxv4l2videosrc0> height = 480
0:00:01.804181000  2228  0x157d6a0 DEBUG        imxv4l2videosrc ../src/v4l2src/v4l2src.c:226:gst_imx_v4l2src_start:<imxv4l2videosrc0> sizeimage = 460800
0:00:01.804324334  2228  0x157d6a0 DEBUG        imxv4l2videosrc ../src/v4l2src/v4l2src.c:227:gst_imx_v4l2src_start:<imxv4l2videosrc0> pixelformat = 842093913
0:00:01.804477000  2228  0x157d6a0 LOG          imxv4l2videosrc ../src/v4l2src/v4l2src.c:927:v4l2_s_ctrl:<imxv4l2videosrc0> VIDIOC_S_CTRL(V4L2_CID_FOCUS_AUTO, 0)
0:00:01.804681667  2228  0x157d6a0 LOG          imxv4l2videosrc ../src/v4l2src/v4l2src.c:934:v4l2_s_ctrl:<imxv4l2videosrc0> VIDIOC_S_CTRL(V4L2_CID_FOCUS_AUTO, 0) failed
0:00:01.804848334  2228  0x157d6a0 LOG          imxv4l2videosrc ../src/v4l2src/v4l2src.c:927:v4l2_s_ctrl:<imxv4l2videosrc0> VIDIOC_S_CTRL(V4L2_CID_AUTO_FOCUS_STOP, 0)
0:00:01.805011667  2228  0x157d6a0 LOG          imxv4l2videosrc ../src/v4l2src/v4l2src.c:934:v4l2_s_ctrl:<imxv4l2videosrc0> VIDIOC_S_CTRL(V4L2_CID_AUTO_FOCUS_STOP, 0) failed
0:00:01.808861334  2228  0x157d6a0 LOG          imxv4l2videosrc ../src/v4l2src/v4l2src.c:915:v4l2_g_ctrl:<imxv4l2videosrc0> VIDIOC_G_CTRL(V4L2_CID_3A_LOCK) returned 0
0:00:01.809038667  2228  0x157d6a0 LOG          imxv4l2videosrc ../src/v4l2src/v4l2src.c:927:v4l2_s_ctrl:<imxv4l2videosrc0> VIDIOC_S_CTRL(V4L2_CID_FOCUS_RANGE, 0)
0:00:01.809219667  2228  0x157d6a0 LOG          imxv4l2videosrc ../src/v4l2src/v4l2src.c:934:v4l2_s_ctrl:<imxv4l2videosrc0> VIDIOC_S_CTRL(V4L2_CID_FOCUS_RANGE, 0) failed
Pipeline is live and does not need PREROLL ...
0:00:01.811787667  2228  0x14c9db0 INFO         imxv4l2videosrc ../src/v4l2src/v4l2src.c:386:gst_imx_v4l2src_negotiate:<imxv4l2videosrc0> negotiated caps video/x-raw, format=(string)I420, width=(int)640, height=(int)480, interlace-mode=(string)progressive, framerate=(fraction)30/1, pixel-aspect-ratio=(fraction)1/1
0:00:01.812757667  2228  0x14c9db0 INFO         imxv4l2videosrc ../src/v4l2src/v4l2src.c:418:gst_imx_v4l2src_set_caps:<imxv4l2videosrc0> set caps video/x-raw, format=(string)I420, width=(int)640, height=(int)480, interlace-mode=(string)progressive, framerate=(fraction)30/1, pixel-aspect-ratio=(fraction)1/1
Setting pipeline to PLAYING ...
0:00:01.817950667  2228  0x14c9db0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:357:gst_imx_v4l2_buffer_pool_init:<GstImxV4l2BufferPool@0x76002010> initializing V4L2 buffer pool
New clock: GstSystemClock
0:00:01.818761000  2228  0x14c9db0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:105:gst_imx_v4l2_buffer_pool_set_config:<imxv4l2bufferpool0> set_config: size 460800, min 6, max 0
0:00:01.847141667  2228  0x14c9db0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:301:gst_imx_v4l2_buffer_pool_start:<imxv4l2bufferpool0> start
0:00:01.847464000  2228  0x14c9db0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:149:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0> alloc 0 0x76003008
0:00:01.848540334  2228  0x14c9db0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:285:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0> qbuf 0 0x76003008
0:00:01.848769334  2228  0x14c9db0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:149:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0> alloc 1 0x760030a8
0:00:01.849033667  2228  0x14c9db0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:285:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0> qbuf 1 0x760030a8
0:00:01.849486000  2228  0x14c9db0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:149:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0> alloc 2 0x76003148
0:00:01.849750334  2228  0x14c9db0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:285:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0> qbuf 2 0x76003148
0:00:01.850819334  2228  0x14c9db0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:149:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0> alloc 3 0x760031e8
0:00:01.851316334  2228  0x14c9db0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:285:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0> qbuf 3 0x760031e8
0:00:01.851513667  2228  0x14c9db0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:149:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0> alloc 4 0x76003288
0:00:01.851950334  2228  0x14c9db0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:285:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0> qbuf 4 0x76003288
0:00:01.852158667  2228  0x14c9db0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:149:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0> alloc 5 0x76003328
0:00:01.852620667  2228  0x14c9db0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:285:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0> qbuf 5 0x76003328
0:00:01.914260334  2228  0x14c9db0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:251:gst_imx_v4l2_buffer_pool_acquire_buffer:<imxv4l2bufferpool0> dqbuf 0 0x76003008
0:00:01.914691667  2228  0x14c9db0 LOG          imxv4l2videosrc ../src/v4l2src/v4l2src.c:323:gst_imx_v4l2src_fill:<imxv4l2videosrc0> fill
0:00:02.050048667  2228  0x14c9db0 LOG           imxphysmemmeta ../src/common/phys_mem_meta.c:67:gst_imx_phys_mem_meta_transform: not copying metadata: only a region is being copied (not the entire block)
0:00:02.051552334  2228  0x14c9db0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:285:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0> qbuf 0 0x76003008
0:00:02.054549667  2228  0x14c9db0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:251:gst_imx_v4l2_buffer_pool_acquire_buffer:<imxv4l2bufferpool0> dqbuf 1 0x760030a8
0:00:02.054767334  2228  0x14c9db0 LOG          imxv4l2videosrc ../src/v4l2src/v4l2src.c:323:gst_imx_v4l2src_fill:<imxv4l2videosrc0> fill
0:00:02.187814334  2228  0x14c9db0 LOG           imxphysmemmeta ../src/common/phys_mem_meta.c:67:gst_imx_phys_mem_meta_transform: not copying metadata: only a region is being copied (not the entire block)
0:00:02.188131334  2228  0x14c9db0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:285:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0> qbuf 1 0x760030a8
Got EOS from element "pipeline0".
Execution ended after 0:00:00.371769667
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
0:00:02.191433334  2228  0x157d6a0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:330:gst_imx_v4l2_buffer_pool_stop:<imxv4l2bufferpool0> stop
0:00:02.206984000  2228  0x157d6a0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:223:gst_imx_v4l2_buffer_pool_free_buffer:<imxv4l2bufferpool0> free 0 0x76003008
Caught SIGSEGV
#0  __libc_do_syscall ()
#1  0x76d423e2 in __libc_waitpid (pid=2232, stat_loc=<optimized out>, 
#2  0x76d9026c in g_on_error_stack_trace ()
#3  0x0000c622 in fault_spin () at gst-launch.c:99
#4  fault_handler_sighandler (signum=<optimized out>) at gst-launch.c:90
#5  <signal handler called>
#6  0x76f30c1e in gst_imx_v4l2_buffer_pool_free_buffer ()
#7  0x76e9df70 in default_stop (pool=0x76002010) at gstbufferpool.c:382
#8  0x76f30fe2 in gst_imx_v4l2_buffer_pool_stop ()
#9  0x76e9dd9e in do_stop (pool=0x76002010) at gstbufferpool.c:402
#10 0x76e9e72a in gst_buffer_pool_set_active (pool=0x76002010, active=0)
#11 0x76ad941a in gst_base_src_activate_pool (basesrc=<optimized out>, 
#12 0x76ad9524 in gst_base_src_set_flushing (basesrc=0x159e178, flushing=1, 
#13 0x76ad9a98 in gst_base_src_stop (basesrc=0x159e178) at gstbasesrc.c:3402
#14 0x76adebaa in gst_base_src_activate_push (active=<optimized out>, 
#15 gst_base_src_activate_mode (pad=0x15a0020, parent=0x159e178, 
#16 0x76ec040c in gst_pad_activate_mode (pad=0x15a0020, 
#17 0x76ec0b8e in gst_pad_set_active (pad=0x15a0020, active=0) at gstpad.c:969
#18 0x76eab010 in activate_pads (vpad=<optimized out>, ret=0x7ec4a570, 
#19 0x76eb67ec in gst_iterator_fold (it=0x15a9540, 
#20 0x76eab23a in iterator_activate_fold_with_resync (iter=0x15a9540, 
#21 0x76eac8c2 in gst_element_pads_activate (element=0x159e178, active=0)
#22 0x76eacb62 in gst_element_change_state_func (element=0x159e178, 
#23 0x76add4c8 in gst_base_src_change_state (element=0x159e178, 
#24 0x76eae042 in gst_element_change_state (element=0x159e178, 
#25 0x76eae70a in gst_element_set_state_func (element=0x159e178, 
#26 0x76eade5a in gst_element_set_state (element=0x159e178, 
#27 0x76e9a7bc in gst_bin_element_set_state (next=GST_STATE_READY, 
#28 gst_bin_change_state_func (element=0x15a8098, 
#29 0x76ec56fe in gst_pipeline_change_state (element=0x15a8098, 
#30 0x76eae042 in gst_element_change_state (element=0x15a8098, 
#31 0x76eae70a in gst_element_set_state_func (element=0x15a8098, 
#32 0x76eade5a in gst_element_set_state (element=0x15a8098, 
#33 0x0000b35a in main (argc=8, argv=0x7ec4ac44) at gst-launch.c:1142
Spinning.  Please run 'gdb gst-launch-1.0 2228' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core.

**Comment by dv1** [comment] 2015-11-03 09:47
I can still not reproduce it. I am running it on a nitrogen6x board. However, it is using an ov5642, not an ov5640. I'll retry it on an imx6dlsabresd, I think these have an ov5640. What hardware are you using, and what kernel version?

Also try out the imxvpuapi-integration branch, and note that in this branch, the num-buffers=2 trick is no longer necessary. You can use num-buffers=1 now.

**Comment by dv1** [comment] 2015-11-03 16:40
No, the Sabre SD also has a 5642. Still, I have a suspicion of what is going on. Can you try out this patch? https://www.dropbox.com/s/z2btpaqztu2vdu4/v4l2-possible-fix.patch
Also, rebuild gstreamer-imx with the --enable-debug configure switch to get the line numbers in the backtrace.

**Comment by cottrelld** [comment] 2015-11-03 18:10
Thanks for looking into it, we'll be able to test it out tomorrow night.  We'll report back the results for the patch, branch and line numbers.

**Comment by cottrelld** [comment] 2015-11-05 16:52
Your patch worked when applied to master, no more crash.  Thanks!

# GST_DEBUG=2,imxv4l2bufferpool:9,imx:9 gst-launch-1.0 imxv4l2videosrc num-buffers=2 ! jpegenc ! filesink location=sample.jpeg
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
0:00:01.531434667 12369   0x6b5fb0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:359:gst_imx_v4l2_buffer_pool_init:<GstImxV4l2BufferPool@0x6ce008> initializing V4L2 buffer pool
0:00:01.532577334 12369   0x6b5fb0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:105:gst_imx_v4l2_buffer_pool_set_config:<imxv4l2bufferpool0> set_config: size 460800, min 6, max 0
Setting pipeline to PLAYING ...
New clock: GstSystemClock
0:00:01.570144667 12369   0x6b5fb0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:301:gst_imx_v4l2_buffer_pool_start:<imxv4l2bufferpool0> start
0:00:01.570473334 12369   0x6b5fb0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:149:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0> alloc 0 0x6cf000
0:00:01.571594667 12369   0x6b5fb0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:285:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0> qbuf 0 0x6cf000
0:00:01.571823001 12369   0x6b5fb0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:149:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0> alloc 1 0x6cf0a0
0:00:01.572088334 12369   0x6b5fb0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:285:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0> qbuf 1 0x6cf0a0
0:00:01.572563667 12369   0x6b5fb0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:149:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0> alloc 2 0x6cf140
0:00:01.572946334 12369   0x6b5fb0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:285:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0> qbuf 2 0x6cf140
0:00:01.573138001 12369   0x6b5fb0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:149:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0> alloc 3 0x6cf1e0
0:00:01.573402334 12369   0x6b5fb0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:285:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0> qbuf 3 0x6cf1e0
0:00:01.573585001 12369   0x6b5fb0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:149:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0> alloc 4 0x6cf280
0:00:01.574130001 12369   0x6b5fb0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:285:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0> qbuf 4 0x6cf280
0:00:01.574335667 12369   0x6b5fb0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:149:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0> alloc 5 0x6cf320
0:00:01.574737334 12369   0x6b5fb0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:285:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0> qbuf 5 0x6cf320
0:00:01.630977667 12369   0x6b5fb0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:251:gst_imx_v4l2_buffer_pool_acquire_buffer:<imxv4l2bufferpool0> dqbuf 0 0x6cf000
0:00:01.774575667 12369   0x6b5fb0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:285:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0> qbuf 0 0x6cf000
0:00:01.777044334 12369   0x6b5fb0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:251:gst_imx_v4l2_buffer_pool_acquire_buffer:<imxv4l2bufferpool0> dqbuf 1 0x6cf0a0
0:00:01.868919667 12369   0x6b5fb0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:285:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0> qbuf 1 0x6cf0a0
Got EOS from element "pipeline0".
Execution ended after 0:00:00.331366000
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
0:00:01.870545334 12369   0x6bb5c0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:330:gst_imx_v4l2_buffer_pool_stop:<imxv4l2bufferpool0> stop
0:00:01.886966334 12369   0x6bb5c0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:223:gst_imx_v4l2_buffer_pool_free_buffer:<imxv4l2bufferpool0> free 0 0x6cf000
0:00:01.887105001 12369   0x6bb5c0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:223:gst_imx_v4l2_buffer_pool_free_buffer:<imxv4l2bufferpool0> free 1 0x6cf0a0
0:00:01.887186334 12369   0x6bb5c0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:223:gst_imx_v4l2_buffer_pool_free_buffer:<imxv4l2bufferpool0> free 2 0x6cf140
0:00:01.887260667 12369   0x6bb5c0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:223:gst_imx_v4l2_buffer_pool_free_buffer:<imxv4l2bufferpool0> free 3 0x6cf1e0
0:00:01.887331667 12369   0x6bb5c0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:223:gst_imx_v4l2_buffer_pool_free_buffer:<imxv4l2bufferpool0> free 4 0x6cf280
0:00:01.887409001 12369   0x6bb5c0 DEBUG      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:223:gst_imx_v4l2_buffer_pool_free_buffer:<imxv4l2bufferpool0> free 5 0x6cf320
0:00:01.891585001 12369   0x6bb5c0 TRACE      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:371:gst_imx_v4l2_buffer_pool_finalize:<imxv4l2bufferpool0> shutting down buffer pool
Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by dv1** [comment] 2015-11-05 17:06
Great! I'll commit this then.

**Closed** 2015-11-05 22:46 UTC
