### ISSUE TITLE
imxvpudec problem: "Could not push input frame data into decoder: invalid call"

### ISSUE THREAD

**Issue by guillerodriguez** [Freescale/gstreamer-imx#293] opened 2021-07-05 16:10 UTC
I am trying to test a basic RTSP / H.264 pipeline as follows:

```
gst-launch-1.0 rtspsrc location=rtsp://192.168.0.241 ! rtph264depay ! h264parse ! imxvpudec_h264 ! imxg2dvideosink clear-at-null=true
```

This fails with the following error messages, and nothing shown onscreen:

```
[...]
0:00:02.346060667  0x75003750 ERROR            imxvpuapi imxvpuapi2_imx6_coda.c:1949:imx_vpu_api_dec_push_encoded_frame: tried to push an encoded frame before a previous one was decoded
0:00:02.346159667  0x75003750 ERROR            imxvpudec gstimxvpudec.c:629:gst_imx_vpu_dec_handle_frame:<imxvpudech264-0> could not push input frame data into decoder: invalid call
0:00:02.346554667  0x75003750 ERROR            imxvpuapi imxvpuapi2_imx6_coda.c:1949:imx_vpu_api_dec_push_encoded_frame: tried to push an encoded frame before a previous one was decoded
0:00:02.346615000  0x75003750 ERROR            imxvpudec gstimxvpudec.c:629:gst_imx_vpu_dec_handle_frame:<imxvpudech264-0> could not push input frame data into decoder: invalid call
0:00:02.346849667  0x75003750 ERROR            imxvpuapi imxvpuapi2_imx6_coda.c:1949:imx_vpu_api_dec_push_encoded_frame: tried to push an encoded frame before a previous one was decoded
0:00:02.346897333  0x75003750 ERROR            imxvpudec gstimxvpudec.c:629:gst_imx_vpu_dec_handle_frame:<imxvpudech264-0> could not push input frame data into decoder: invalid call
[...continues...]
```

Same happens with imxvpudec_mpeg4 although surprisingly imxvpudec_jpeg works.

Replacing imxg2dvideosink with fbdevsink doesn't help. Adding some queues to the pipeline doesn't help either.

Versions:
 * gstreamer-imx-2.0.0
 * libimxvpuapi-2.1.2
 * libimxdmabuffer-1.0.1
 * imx-vpu-5.4.37
 * Kernel: 5.4.85 with patches from https://github.com/varigit/linux-imx/tree/5.4-2.1.x-imx_var01
 * Vivante kernel module + libs: 6.4.0.p2.4

Any hint what could be happening here ?

**Comment by dv1** [comment] 2021-07-08 06:12
This is indeed odd. Does this happen with any RTSP h264 signal? How did you generate the signal? Did you use VLC or gst-rtsp-server?

**Comment by guillerodriguez** [comment] 2021-07-08 17:57
This is with a live RTSP stream coming from an IP door station. The same setup was working fine with the 0.x series (been using 0.13.1 until now).

I will try with other stream sources and report back.

**Comment by guillerodriguez** [comment] 2021-07-16 07:53
@dv1 Have tried other RTSP live sources (IP cameras and door stations), same problem. All of these work fine with the 0.x series.

Also tried using gst-rtsp-server:

```
./test-launch  --gst-debug=3 '( v4l2src device=/dev/video0 ! videoconvert ! video/x-raw,width=320,height=240 ! x264enc tune="zerolatency" ! video/x-h264, profile=baseline ! rtph264pay name=pay0 pt=96 )'
```

The above works fine with 0.13.1. With 2.0.0 it seems to be hit and miss, either it works fine, or it starts dumping "tried to push an encoded frame before a previous one was decode" + "invalid call" error messages and nothing is shown onscreen. It seems to work like 50% of the time...

Any hints?

**Comment by guillerodriguez** [comment] 2021-07-20 18:19
@dv1 Any other tests I can run? Anything else I can do?

**Comment by dv1** [comment] 2021-07-26 20:48
@guillerodriguez Unfortunately I am dealing with something else at the moment. I'll try to make some room for this in a couple of days.

**Comment by dv1** [comment] 2021-08-17 08:08
I could not reproduce this yet. Can you reproduce this on a Sabre SD board?

**Comment by guillerodriguez** [comment] 2021-09-07 11:39
> I could not reproduce this yet. Can you reproduce this on a Sabre SD board? Also, can you re-run this with the `GST_DEBUG` environment variable set to `*vpu*:9` and attach the logs?

Hi, sorry for the delay, I did not have the test setup at hand.
I don't have a Sabre SD board, I am doing all tests on a Variscite [VAR-SOM-SOLO/DUAL](https://www.variscite.com/product/system-on-module-som/cortex-a9/var-som-solo-cpu-nxp-imx6/) + [eval kit](https://www.variscite.com/product/evaluation-kits/var-som-solo-kits/).

However I can re-run with GST_DEBUG set to *vpu*:9 and attach the logs.

Test setup:
 * gstreamer-imx-2.0.0
 * libimxvpuapi2-2.2.0
 * libimxdmabuffer-1.0.1
 * imx-vpu-5.4.39.3
 * Kernel: 5.4.85 + [patches from Variscite]
 * Vivante kernel module + libs: 6.4.0.p2.4

RTSP source using gst-rtsp-server:

```
./test-launch  --gst-debug=3 '( v4l2src device=/dev/video0 ! videoconvert ! video/x-raw,width=320,height=240
! x264enc tune="zerolatency" ! video/x-h264, profile=baseline ! rtph264pay name=pay0 pt=96 )'
```

Gstreamer pipeline:

```
GST_DEBUG_FILE=/tmp/gst.log GST_DEBUG=*vpu*:9 gst-launch-1.0 rtspsrc location=rtsp://192.168.0.155:8554/test
! rtph264depay ! h264parse ! imxvpudec_h264 ! imxg2dvideosink clear-at-null=true
```

As described in [my earlier comment](https://github.com/Freescale/gstreamer-imx/issues/293#issuecomment-896980150), this sometimes work, sometimes doesn't. Seems to be hit and miss.

I am attaching the logs of one of the cases where it did NOT work. The symptoms:
 * Nothing shown onscreen
 * Lots of error messages mentioning "tried to push an encoded frame before a previous one was decoded" and "could not push input frame data into decoder: invalid call"

**Comment by guillerodriguez** [comment] 2021-10-04 08:05
@dv1 Any news? Anything else I can do to help?

**Comment by dv1** [comment] 2021-11-04 08:59
@guillerodriguez Finally got a chance to check it out. Interestingly, trying to play this with vlc, ffplay, gst-play, mpv produces different initial results. Something is wrong with the first few frames. I suspect the bitstream is subtly broken, leading to undefined behavior. Still verifying.

**Comment by guillerodriguez** [comment] 2021-12-05 07:51
@dv1 Any updates on this? Anything I can do to help, please let me know

**Comment by dv1** [comment] 2021-12-07 11:09
@guillerodriguez I have to take care of other issues atm, but I can get back to this in a few days Sorry for the delay.

**Comment by guillerodriguez** [comment] 2022-03-23 12:42
Hi @dv1

> @guillerodriguez I have to take care of other issues atm, but I can get back to this in a few days Sorry for the delay.

Just wanted to check the status of this.
Can I help in any way to make this move forward?

**Comment by dv1** [comment] 2022-04-15 14:45
I ran this as the sender:

    ./test-launch  --gst-debug=3 '( v4l2src device=/dev/video0 ! videoconvert ! video/x-raw,width=320,height=240 ! x264enc tune="zerolatency" ! video/x-h264, profile=baseline ! rtph264pay name=pay0 pt=96 )'

and this on an imx6dl sabre SD:

    GST_DEBUG=2,*imx*:4 gst-launch-1.0 rtspsrc location=rtsp://172.16.1.14:8554/test ! rtph264depay ! h264parse ! imxvpudec_h264 ! imxg2dvideosink clear-at-null=true

and I do not get any errors.

However, this is on Yocto/OE Dunfell, the newest git master versions of gstreamer-imx, and libimxvpuapi 2.2.0. Can you retry with those? And do you use Buildroot or Yocto?

Also, I use GStreamer 1.18.2 on the Sabre board and 1.18.5 on the host. Dunfell has the NXP fork of GStreamer 1.16 by default, so I add the Dunfell branch of https://github.com/OSSystems/meta-gstreamer1.0 and added this to my OE `local.conf` to ensure that the NXP fork is not picked by bitbake:

```
PREFERRED_VERSION_gstreamer1.0 = ""
PREFERRED_VERSION_gstreamer1.0-plugins-base = ""
PREFERRED_VERSION_gstreamer1.0-plugins-good = ""
PREFERRED_VERSION_gstreamer1.0-plugins-bad = ""
PREFERRED_VERSION_gstreamer1.0-libav = ""
```

Can you try that? Perhaps it is a mix of gstreamer-imx and GStreamer issues. I suspect that what you saw is caused by incomplete frames, which can occur over RTSP.

**Comment by dv1** [comment] 2022-06-22 19:32
Indeed the issue persists. The main cause is this:

> imxvpuapi imxvpuapi2_imx6_coda.c:2348:imx_vpu_api_dec_decode: not enough input data was available

Something is off with the incoming h264 data - h264parse is not producing whole frames, or at least the first frame is incomplete. In v1, this incomplete frame was sort of ignored, that is, its PTS/DTS/context values were overwritten by followup frames. In v2, doing that produces an error. Not sure yet how to fix this - if I turn off the check, I get working playback, but the first second or so is just a green frame (not unexpected since the data seems corrupted).

**Comment by guillerodriguez** [comment] 2022-06-23 09:38
> [...] if I turn off the check, I get working playback, but the first second or so is just a green frame (not unexpected since the data seems corrupted). Did you get a green frame at first with v1?

Yes, with v1 I get a green frame for the first second or so, then after a while I see the video playback correctly.

**Comment by guillerodriguez** [comment] 2022-06-24 09:59
Hi,

> @guillerodriguez Can you try applying this patch on libimxvpuapi (not gstreamer-imx!) and retrying? [0001-imx6-coda-Skip-incomplete-frames-instead-of-just-rep.patch.gz](https://github.com/Freescale/gstreamer-imx/files/8960919/0001-imx6-coda-Skip-incomplete-frames-instead-of-just-rep.patch.gz)

Testing this now, preliminary results show that the issue is gone (will need to do more thorough tests).

Is it possible to backport this fix to libimxvpuapi 0.x ?

**Comment by dv1** [comment] 2022-06-25 17:36
> Is it possible to backport this fix to libimxvpuapi 0.x ?

No, this is not feasible. v1 has the problem that you must use a function that blocks until enough framebuffers have been returned to the decoder. There's no way to add framebuffers on the fly. This blocking function causes a lot of problems in more complex GStreamer pipelines where all framebuffers can end up all over the place and can't be returned. Normally, one would then just add more framebuffers, but in v1, that's not doable, as said, so the only tool in that version is to allocate more framebuffers than necessary during initialization. That extra number is arbitrary and needs to be chosen manually, usually by trial and error. v2 solved this in various way depending on the VPU (imx6 vs imx8). I'd have to backport a fair amount of v2 code to v1, which makes no sense. Add to that the fact that I do not have the capacity to maintain both v1 and v2, and you can see why this just can't be done.

**Comment by dv1** [comment] 2023-06-28 17:23
Closing this, as it seems completed. Reopen if it isn't please.

**Closed by dv1** 2023-06-28 17:23 UTC
