### ISSUE TITLE
not recoverable IPU timeouts 

### ISSUE THREAD

**Issue by dierberg** [Freescale/gstreamer-imx#197] opened 2018-03-23 10:05 UTC
Hi, 
sometimes we got following traces (one pair for each analog techwell video in) from IPU.  Only reboot can resolve situation. What is the reason and is it possible to reset IPU to avoid system reboot? Thx.
 
 kernel: mxc_ipu mxc_ipu: ERR: [0xecf85400] no-0x497a50, timeout:1000ms!
 kernel: mxc_ipu mxc_ipu: ERR: [0xecf85400] no-0x497a50, timeout:1000ms!
 kernel: mxc_ipu mxc_ipu: ERR: no-0x497a50,ipu_queue_task err:-110
 kernel: mxc_ipu mxc_ipu: ERR: no-0x497a50,ipu_queue_task err:-110
 kernel: mxc_ipu mxc_ipu: ERR: [0xed0cf000] no-0x497fb0, timeout:1000ms!
 kernel: mxc_ipu mxc_ipu: ERR: [0xed0cf000] no-0x497fb0, timeout:1000ms!
 kernel: mxc_ipu mxc_ipu: ERR: no-0x497fb0,ipu_queue_task err:-110
 kernel: mxc_ipu mxc_ipu: ERR: no-0x497fb0,ipu_queue_task err:-110

**Comment by marioecht** [comment] 2018-12-19 09:59
Hi,

following script triggers the error:


    #!/bin/bash
    
    for DEVICE in $(seq 0 7 );
    do
        gst-launch-1.0 -v  \
                videotestsrc ! \
                "video/x-raw, format=UYVY, width=720, height=576, interlace-mode=interleaved, framerate=12/1, pixel-aspect-ratio=1/1" ! \
                imxipuvideotransform deinterlace=true input-crop=true ! \
                "video/x-raw, width=704, height=576, pixel-aspect-ratio=45/44, format=NV12, is-live=true" ! \
                tee name=tp \
                tp. ! queue ! \
                        videorate max-rate=10 drop-only=true ! \
                        "video/x-raw, framerate=10/1" ! \
                        videoscale ! \
                        "video/x-raw, width=704, height=288" ! \
                        imxvpuenc_h264 gop-size=50 idr-interval=50 me-search-range=3 ! \
                        fakesink \
                tp. ! queue ! \
                        imxipuvideotransform  input-crop=true ! \
                        "video/x-raw, width=640,  height=360" ! \
                        imxvpuenc_h264 gop-size=15 idr-interval=15 bitrate=2000 me-search-range=3 ! \
                        fakesink 2>&1 | logger &
        sleep 1
    done

    sleep infinity

i.MX6Q
kernel: 4.9.88
gstreamer1.0-plugins-imx: 0.13

Without deinterlace (imxipuvideotransform deinterlace=false), the error does not happen.
Probably the problem is in kernel driver (drivers/mxc/ipu3/ipu_device.c).

Who can help here?

**Comment by angolini** [comment] 2021-08-16 14:09
gstreamer 0.x is no longer supported (I don't remember when it was deprecated, but it was a looong time ago). So I'm closing this issue.

In case there is still any help needed or any issue, please test using the latest version and create a new issue. Thanks a lot!

**Closed by angolini** 2021-08-16 14:09 UTC

**Comment by dierberg** [comment] 2021-08-16 14:17
@angolini Sorry, but this is not a gstreamer 0.x issue!

**Comment by angolini** [comment] 2021-08-16 14:21
Oh! That's the problem of reading things too fast.

@dierberg , could you, please, test with latest versions and share what is the current behavior? You can reopen the issue.

**Comment by dierberg** [comment] 2021-08-16 14:33
We will use the new version of gstreamer-imx with Yocto hardknott next weeks. Any problems will be published.
