### ISSUE TITLE
imxvpuenc_h264 does't close all sockets on shut down operation

### ISSUE THREAD

**Issue by angelobt** [Freescale/gstreamer-imx#59] opened 2015-09-28 14:04 UTC
I have this pipeline built with gstreamer libraries.

imxv4l2videosrc -> caps(720x576 UYVY 25 fps) -> imxipuvideotransform -> caps(720x576 I420 25 fps) -> imxvpuenc_h264->fakesink

every time I set pipeline to PLAYING STATE and then to NULL state, the number of open sockets increases by 1. 

I have tried to modify the pipeline as follow

imxv4l2videosrc -> caps(720x576 UYVY 25 fps) -> imxipuvideotransform -> caps(720x576 I420 25 fps) -> fakesink

and without encoder the number of socket does't raise.

**Comment by angelobt** [comment] 2015-09-28 14:34
Same problem with imxvpuenc_mjpeg. I think is something in the common code about vpu plugins

**Comment by dv1** [comment] 2015-09-28 20:01
Does this also happen if you check out the imxvpuapi-integration branch and use the --use-vpulib-backend option in ./waf configure ?

**Comment by angelobt** [comment] 2015-09-29 07:32
Unfortunately, it does

this is the fd status between two calls

dr-x------ 2 root root  0 Sep 11 15:57 .
dr-xr-xr-x 7 root root  0 Sep 11 15:56 ..
lr-x------ 1 root root 64 Sep 11 15:57 0 -> /dev/null
lrwx------ 1 root root 64 Sep 11 15:57 1 -> /dev/console
lrwx------ 1 root root 64 Sep 11 15:57 15 -> socket:[5039]
lrwx------ 1 root root 64 Sep 11 15:57 16 -> socket:[5040]
lrwx------ 1 root root 64 Sep 11 15:57 17 -> socket:[5066]
lrwx------ 1 root root 64 Sep 11 15:57 2 -> /dev/console
lrwx------ 1 root root 64 Sep 11 15:57 20 -> socket:[5321]
lrwx------ 1 root root 64 Sep 11 15:57 21 -> socket:[5322]
l-wx------ 1 root root 64 Sep 11 15:57 3 -> /var/volatile/tmp/bt_av_media.log
lrwx------ 1 root root 64 Sep 11 15:57 4 -> anon_inode:[eventfd]
lrwx------ 1 root root 64 Sep 11 15:57 5 -> socket:[4631]
lrwx------ 1 root root 64 Sep 11 15:57 6 -> socket:[4632]
lrwx------ 1 root root 64 Sep 11 15:57 7 -> socket:[4663]
lrwx------ 1 root root 64 Sep 11 15:57 8 -> socket:[5065]





lr-x------ 1 root root 64 Sep 11 15:57 0 -> /dev/null
lrwx------ 1 root root 64 Sep 11 15:57 1 -> /dev/console
lrwx------ 1 root root 64 Sep 11 15:57 15 -> socket:[5039]
lrwx------ 1 root root 64 Sep 11 15:57 16 -> socket:[5040]
lrwx------ 1 root root 64 Sep 11 15:57 17 -> socket:[5066]
lrwx------ 1 root root 64 Sep 11 15:59 19 -> socket:[5578]
lrwx------ 1 root root 64 Sep 11 15:57 2 -> /dev/console
lrwx------ 1 root root 64 Sep 11 15:57 20 -> socket:[5321]
lrwx------ 1 root root 64 Sep 11 15:57 21 -> socket:[5322]
lrwx------ 1 root root 64 Sep 11 15:59 22 -> socket:[5579]
l-wx------ 1 root root 64 Sep 11 15:57 3 -> /var/volatile/tmp/bt_av_media.log
lrwx------ 1 root root 64 Sep 11 15:57 4 -> anon_inode:[eventfd]
lrwx------ 1 root root 64 Sep 11 15:57 5 -> socket:[4631]
lrwx------ 1 root root 64 Sep 11 15:57 6 -> socket:[4632]
lrwx------ 1 root root 64 Sep 11 15:57 7 -> socket:[4663]
lrwx------ 1 root root 64 Sep 11 15:57 8 -> socket:[5065]

**Comment by dv1** [comment] 2015-09-29 07:51
Can you give me an example program that demonstrates this?

**Comment by angelobt** [comment] 2015-09-29 12:54
Here you can find an example

http://pastebin.com/W4XQhzzZ

Please try to create and destroy the first pipeline (press 1 and 4).

Seems that the problem happens if imxipuvideotransform and imxvpuenc_h264 are used at the same time.

if you try to create and desroy pipelines 2 and 3, all goes well.

**Comment by angelobt** [comment] 2015-10-02 08:52
Hi, did you have time to have a look about the issue ?
If you need more logs/informations, I'm available to do other tests.

**Comment by dv1** [comment] 2015-10-02 08:53
Not yet. I am currently working on VPU related stuff though, so I'll check it out as well.

**Comment by dv1** [comment] 2015-10-04 15:34
OK, I had a look at this, and am honestly puzzled. A test run with strace shows that something is calling socketpair(), and a few processes are spawned. I currently do not have the faintest idea why. I am continuing to investigate.

**Comment by dv1** [comment] 2015-11-10 13:19
Fixed in commit d8d7ea3 . The cause was somewhere else entirely - a buffer pool in the video transform wasn't being unref'd, and this pool created a pair of socket FDs.

**Closed by dv1** 2015-11-10 13:19 UTC
