### ISSUE TITLE
"imxipuvideotransform" with "imxvpuenc_h264" not working(green screen on ArchLinux ARM)

### ISSUE THREAD

**Issue by n-aizu** [Freescale/gstreamer-imx#27] opened 2015-01-29 13:58 UTC
The following was not working on ArchLinux ARM. I get a green picture.

```
gst-launch-1.0 videotestsrc num-buffers=2000 pattern=0 ! video/x-raw,format="RGB",width=1280,height=960,framerate=30/1 ! \
imxipuvideotransform ! imxvpuenc_h264 idr-interval=16 ! h264parse ! mpegtsmux ! filesink location=testh264.mts
```

HardWare:
SolidRun's Hummingboard(i.MX6 quad)

SoftWare:
ArchLinuxARM-imx6-cubox-latest.tar.gz - 02-Jan-2015 version

```
[root@alarm ~]# pacman -Ss gst-imx
alarm/gst-imx 0.10.0-5 [installed]
    GStreamer plugins for i.MX platforms

[root@alarm ~]# pacman -Ss firmware-imx
alarm/firmware-imx 3.10.17_1.0.0-1 [installed]
    Freescale proprietary firmware for i.MX6 SoC
```

**Comment by dv1** [comment] 2015-02-10 16:27
This is actually not encoder specific. This pipeline shows the same problem:

    gst-launch-1.0 videotestsrc ! "video/x-raw, format=RGBA" ! imxipuvideotransform ! "video/x-raw, format=I420" ! imxg2dvideosink

**Comment by dv1** [comment] 2015-02-10 18:31
I got a fix in the latest commit.  Can you try it out if it solves your case?

**Comment by n-aizu** [comment] 2015-02-11 07:04
Green picture is fixed. But ipu driver puts warning messages.
```
[  364.444532] imx-ipuv3 2800000.ipu: IDMAC21's V offset is not 8-byte aligned
[  364.451644] imx-ipuv3 2800000.ipu: IDMAC22's U offset is not 8-byte aligned
[  364.458692] imx-ipuv3 2800000.ipu: IDMAC22's V offset is not 8-byte aligned
[  364.475305] imx-ipuv3 2800000.ipu: IDMAC21's U offset is not 8-byte aligned
```
The picture is near normal, but there are green several pixels on the right end.

When I set "width=640,height=480", this ipu issue was not reproduced.
And also "format=Y444" was normal.

normal:
```
gst-launch-1.0 videotestsrc num-buffers=2000 pattern=0 ! video/x-raw,format="RGB",width=1280,height=960,framerate=15/1 ! \
imxipuvideotransform ! video/x-raw,format=Y444,width=1280,height=960,framerate=15/1 ! filesink location=test.dat
```

error:
```
gst-launch-1.0 videotestsrc num-buffers=2000 pattern=0 ! video/x-raw,format="RGB",width=1280,height=960,framerate=15/1 ! \
imxipuvideotransform ! video/x-raw,format=I420,width=1280,height=960,framerate=15/1 ! filesink location=test.dat
```

I updated all ArchLinux pacages and rebuild/reinstall latest gstreamer-imx, but this ipu issue was not fiexed.
(I removed gst-imx package before install latest version)

**Comment by dv1** [comment] 2015-02-11 11:13
Right. This is unfortunately tricky to fix, and one of the many IPU idiosyncrasies. I'll do this in the next few days.

**Comment by dv1** [comment] 2015-02-13 22:03
I investigated this further. This is a bug buried deep inside the IPU driver. The IPU cannot output to fields larger than 1024x1024 at once. The driver then splits the blit task into stripes. For unknown reasons, it subtracts 16 pixels. For example, width 1280 becomes 1280-16 = 1264. This value is then halved. The results - 632 - is then the X offset of the second stripe. This is then the basis for some very weird internal calculations, which end up with U/V offsets that are not a multiple of 8.

The only solution I can see for this is to do this striping myself. If either width, height, or both exceed 1024, I'll tile the output. This won't make it in 0.10.1 , however. It will be in the version afterwards.

**Comment by Gateworks** [comment] 2015-09-02 20:50
I'm seeing likely the same issue with the following pipeline:
gst-launch-1.0 videotestsrc ! 'video/x-raw,width=1280,height=720,format=UYVY' ! imxipuvideotransform ! imxvpuenc_h264 ! imxvpudec ! fakesink

The key here is that a transform needs to be done to I420 as that is the only format imxvpuenc accepts.

I've tracked down to the IPU transforming a 720p UYVY to I420 which has to be split into 2 stripes (1280 width > 1024) and ends up getting split into non-equal stripes of 632/648 pixels instead of 640/640 which in turn ends up selecting a u_offset that is not byte aligned.

The 632/648 split is coming from ipu_calc_stripes_sizes() (http://git.freescale.com/git/cgit.cgi/imx/linux-2.6-imx.git/tree/drivers/mxc/ipu3/ipu_calc_stripes_sizes.c?h=imx_3.14.28_1.0.0_ga#n231) and I don't quite undersatnd the math there (not really clear what OF and OM or the _m and _f stuff is - looks like they may be trying to do some integer math to avoid costly floating point divs?)

The function is apparently not able to calculate equal stripes for 1280x720 I420 and says so by returning a value of 2 indicating that 'OF is not a multiple of OM' (if DEBUG enabled in ipu_device.c produces 'Warn: no:0x0,calc_stripes ret:2').

If I enable debugging in ipu_calc_stripes_sizes I see the following
for a transform from 1280x720 UYUV -> 1280x720 I420:
[  181.746788] ---------------->
[  181.746788] if  = 8
[  181.746788] im  = 8
[  181.746788] of = 8
[  181.746788] om = 16
[  181.746788] irr_opt  = 4294967296
[  181.746788] rr_opt   = 4294967296
[  181.746788] cirr     = 4294967296
[  181.746788] pixel in  = 59565955
[  181.746788] pixel out = 30323449
[  181.746788] ifw = 1280
[  181.746788] ofwidth = 1280
[  181.779405] inw 632, onw 632, ilw 648, ilc 0, olw 648, irw 648, irc
632, orw 648, orc 632, difwr  0, lirr 8192
[  181.789551] imx-ipuv3 2800000.ipu: IDMAC21's U offset is not 8-byte aligned
[  181.796554] imx-ipuv3 2800000.ipu: IDMAC21's V offset is not 8-byte aligned

With the following patch ipu_calc_stripes_sizes a calculates an equal split:
diff --git a/drivers/mxc/ipu3/ipu_calc_stripes_sizes.c b/drivers/mxc/ipu3/ipu_ca
index c466ea9..bf72583 100644
--- a/drivers/mxc/ipu3/ipu_calc_stripes_sizes.c
+++ b/drivers/mxc/ipu3/ipu_calc_stripes_sizes.c
@@ -18,6 +18,7 @@
  *
  * @ingroup IPU
  */
+#define DEBUG

 #include <linux/ipu-v3.h>
 #include <linux/module.h>
@@ -351,7 +352,7 @@ int ipu_calc_stripes_sizes(const unsigned int
input_frame_width,
                                       (right->input_width - 1)),
(right->output_width - 1));
                        left->irr = right->irr = truncate(0, div, 1);
                } else { /* with overlap */
-                       onw = truncate(0, (((u64)output_frame_width -
1) << 32) >> 1,
+                       onw = truncate(0, (((u64)output_frame_width)
<< 32) >> 1,
                                       output_f);
                        inw = truncate(0, onw * irr_opt, input_f);
                        /* this is the maximal inw which allows the
same resizing ratio */

I'm not sure if this is the right fix or if it is am I getting all the off-by-1 errors in that function for the other use cases?

I consider this a kernel IPU driver bug/limitation and not a gstreamer-imx issue as I can get the issue to occur with gst-fsl-plugins as well:

I'm using the following pipeline to test this:
gst-launch-0.10 videotestsrc num-buffers=1 ! 'video/x-raw-yuv,width=1280,height=720,format=(fourcc)UYVY' ! mfw_ipucsc ! 'video/x-raw-yuv,width=1280,height=720,format=(fourcc)I420' ! vpuenc codec=avc ! fakesink

Unfortunately for me this isn't an issue with gst-fsl-plugins as its vpuenc element accepts the UYVY (NV12) without needing a transform yet gstreamer_imx does need a transform as it only accepts I420.

**Comment by dv1** [comment] 2015-09-03 07:48
This hints at a problem with the tiling logic in the IPU driver, which is undocumented, complicated, and confusing. It kicks with resolutions that have either a width or a height larger than 1024. I have had problems with tiling in the past, so the proper fix is to do the tiling manually in gstreamer-imx.

**Comment by Gateworks** [comment] 2015-09-08 13:19
I found another case where I believe Freescale has another off-by-one issue in their resizer math within the ipuv3 driver. Both of these cases can produce image issues with the 2nd stripe that is used when width or height is greater than 1024, even when the width % 8 = 0. The image issues are very apparent if you look at a colorbar pattern - the chromanance will be shifted to the left a few pixels (depending on the stripe width mod 8) which will show up as color-bleed and a visible green bar in the last few vertical lines.

https://github.com/Gateworks/linux-imx6/commit/0d54f90b94a0d968241847226f70e189b15900ea

It is still very easy to run into 8-byte alignment issues with the compositor and unless 8-byte aligned tiling is added into gstreamer-imx its advisable to use the g2d compositor which doesn't suffer from those issues.

I would recommend closing this issue as its not a fault of gstreamer-imx. It is true that implementing 8-byte aligned tiling would avoid the issue and make the imxipucompositor much more useful that would be an enhancement.

**Comment by dv1** [comment] 2015-10-19 19:57
Recently I found another limitation: when scaling, if the ratio src/dest is >= 8, the ipu task fails. This applies to both width and height. So, the ratios src_width/dest_width and src_height/dest_height must both be <8.

I suspect this is caused by the underlying 8x8-tiled nature of the IPU operation. Either way, this complicates matters, since if one ratio is >= 8, then scaling must be done in a multistage process, where each stage scales with a ratio <8.

**Comment by phdm** [comment] 2016-09-07 14:17
@Gateworks , I also had the same problem of kernel messages 'IDMAC21's U offset is not 8-byte aligned' and 'IDMAC21's V offset is not 8-byte aligned', and green columns at left of my image when doing a conversion from RGB4 to I420.  I had also tracked down the problem to ipu_calc_stripes_sizes, but then found your patch.  It works perfectly for me too.  This is with a imx_4.1.15_1.0.0_ga kernel from Freescale/NXP.  Thanks

**Closed** 2019-05-15 19:08 UTC
